# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1855bcc03400f3a62cb83aa04d2f053213ada89d528ecaf99ad9804cfa91f386d1839ff0571d9661102a7f9ab02133a64bc2adc6b57d986c63a760b07be8f8c4

test:
  secret_key_base: 70133df700e94d5981fe90699534a5258c5911e93d72b35f3c9e87d9a6e99017eb6cfde47e22ca8eb47653330fa7463d097e33acadbf2b5cd559bfa566cf9efe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
